### ISSUE TITLE
Files which have common suffix can conflict during target replacement

### ISSUE THREAD

**Issue by cromwellryan** [sparkbox/cachebust#5]
Lets say you have an `mq-base.css` and `no-mq-base.css` file that should both be fingerprinted.

Using this config:
```
  "cachebust": {
    "source": [
      "dist/css/mq-base.css",
      "dist/css/no-mq-base.css",
      "dist/js/Driver-Solutions.min.js"
      ],
      "target": [
        "../templates/default_site/includes.group/site-footer.html",
        "../templates/default_site/includes.group/site-head.html",
        "../templates/default_site/includes.group/site-head-404.html"
      ]
  }
```

You will find an entry in your target with:

```/path/to/no-<fingerprint_for_mq-base.css> .css```

If you switch the order of the source entries such that `no-mq-base` appears before `mq-base` alphabetically, this issue doesn't appear.

**Comment by patricksimpson** [comment]
I will look into a fix for this tomorrow. Maybe alpha sort on the source files? 🤔
